spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver
#  datasource:
#    url: jdbc:mysql://springboot-db2.cvqrxyomkoch.ap-northeast-2.rds.amazonaws.com:3306/mydb
#    username: admin
#    password: dudwlsdl12

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql : true # sql 예쁘게 출력
        default_batch_fetch_size: 1000

    show-sql: true  # sql 출력